test: &default

  # Credentials for REST APIs
  client_id: AXQTDDwydnC-9iJr1xATAFArXILTglRjUV8bttbS3GQgfiVHa5pZk_FryZ6PkXz0f3HKow7m0nTzSESy
  client_secret: EAQUPyv8rWv4sHWfW4UTRSjqnzlZ84wM6p42aS1UzTs_cF0g0T0LZAMxPm55QAZcrSkNL48gxImWIyEq

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: omar@ibsa.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
